# Generated by Django 4.0.4 on 2022-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=32)),
                ('image', models.ImageField(upload_to='images')),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
