# Generated by Django 4.0 on 2023-05-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_sign',
            name='image',
        ),
    ]
